CREATE SCHEMA IF NOT EXISTS history ;

CREATE TABLE project (
  id BIGINT AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE snapshot (
  id BIGINT AUTO_INCREMENT NOT NULL,
  project_id BIGINT NOT NULL,
  shapes_data JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_snapshot_project 
    FOREIGN KEY (project_id) REFERENCES project(id) 
    ON DELETE CASCADE
);

